on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Check if Fmt'ed
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  publish-check:
    name: Publish Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: cargo fetch
      uses: actions-rs/cargo@v1
      with:
        command: fetch
    - name: cargo publish check
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --dry-run

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: 
      - fmt-lint
      - publish-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cargo fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch  
      - name: cargo publish
        uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
  
  build:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - fmt-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: cargo build
        run: cargo build --release && strip target/release/caffeine && mv target/release/caffeine target/release/caffeine_amd64
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/caffeine_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - fmt-lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: cargo build
        run: cargo build --release
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/caffeine.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - fmt-lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true
      - name: cargo build
        run: cargo build --release && strip target/release/caffeine && mv target/release/caffeine target/release/caffeine_darwin
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
              target/release/caffeine_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
